Use `Array.from(map.keys())` instead of `[...map.keys()]` to work around an intermittent Oculus Browser bug causing "Uncaught TypeError: props.keys is not a function or its return value is not iterable".